// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyKW1BJif7gS3yQDW-E6wa5s46f4mk34',
    appId: '1:381554635819:web:99d98e0c2a8a0d7e31666e',
    messagingSenderId: '381554635819',
    projectId: 'tik-tong-insu',
    authDomain: 'tik-tong-insu.firebaseapp.com',
    storageBucket: 'tik-tong-insu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99o8RXIEXOc8C4XV9r_ETAXa8bo6Bn6A',
    appId: '1:381554635819:android:be91ffb3327a09ee31666e',
    messagingSenderId: '381554635819',
    projectId: 'tik-tong-insu',
    storageBucket: 'tik-tong-insu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUWL8BrrWbskbZIhbwkD9mRZx0lca9R4',
    appId: '1:381554635819:ios:12328372359b982c31666e',
    messagingSenderId: '381554635819',
    projectId: 'tik-tong-insu',
    storageBucket: 'tik-tong-insu.firebasestorage.app',
    iosBundleId: 'com.example.tiktong',
  );

}